version: "3.5"

services:
  mongodb:
    image: mongo:4.4.4
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=root

  topology-manager:
    image: brunobevilaquaa/fed-topology-manager
    container_name: topology-manager
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://root:root@mongodb:27017/admin
      - TOP_MAX_REDUNDANCY=5
      - CORE_ANN_INTERVAL=10s
      - BEACON_INTERVAL=10s
      - FED_REDUNDANCY=2

networks:
  default:
    name: federation
    # external: true